### ISSUE TITLE
Ideas for speeding up search

### ISSUE THREAD

**Issue by DigitalAda** [fantomitechno/dd2#1]
Here are some thoughs on ways you could speed up search. These mostly revolve around getting the wsid of a user quickly and then calling the dd2 api with the wsid directly. 

1. Use trackmania.io search api to get user info 
     - This might be good depending on the quality of the search result
     - Docs here <https://github.com/GreepTheSheep/node-trackmania.io/blob/develop/src/managers/PlayerManager.js#L85>
     - Slightly relevant example <https://github.com/GreepTheSheep/node-trackmania.io/blob/develop/examples/playerCOTD.md>
2. Have a long living cache for all leaderboard pages and use that to get the wsid.
     - Would this be viable with the current hosting or would the process go to sleep and kill the cache? 
     - If the api ges to sleep, this requires some form of storage/persistance.
3. Get all 100 pages in parallel instead of doing one at a time.
    - This would make it faster for lower ranked users, but slower for the top ones.
    - This would be a bit more technical to implement but should be doable. 
    - There would be a higher strain of the dd2 api which might annoy the core team.

Hope any of this helps! I'm happy to discuss any of these if you want

**Comment by fantomitechno** [comment]
The first point is already out of the question because the search API exists only because tm.io search is bad 😅 (for example the player OopsTM searched himself in Vaelyn's chat via tm.io but each time his search was polluted by goopsTM that was returned first). 

The tm.io search only looks at if the search is included in the results and not if there're similarities (example: if you use the API to search for simo900, mine will return simo_900, tm.io won't return anything)

The second point is very interesting I already have a cache system that puts API results in a local variable for 20s and reuse them if requested in the 20s interval and I saw with manual testing that asking for a low player two times in a row the second time was faster. I could up the cache only for these requests (because I prefer a low cache for the leaderboard, live ranking etc to be able to display live information).

The third point is interesting too, I'm not sure I like it to request every page in one go but I'll explore this possibility.

Thank you for your help and propositions! ❤️

**Comment by DigitalAda** [comment]
Will the tm.io API only return the first result? I imagine it returns multiple and the issue with oops was that the implementation was getting the first match and not the closest(or in this case exact) match from the API. 

The first two options are mostly intended to quickly find the ID of a user. If you do the search on a cache that lives an hour for example, you can quickly get the ID of a user. Then I think you could call the DD2 API with the user id directly to get their newest score. This would reduce from potentially searching 100 pages of the leaderboard per request to only do a cache lookup and then hit the API once.

I also just thought of a potential bug in the current implementation. Say there was a player named simo900 that has a low ranking. Or if GoopsTm started playing Deep Dip 2 and got a higher place on the leaderboard than OppsTM. Would that not lead to the lower ranking player being hidden by a higher ranking player with a "matching" name?

**Comment by fantomitechno** [comment]
> The first two options are mostly intended to quickly find the ID of a user. If you do the search on a cache that lives an hour for example, you can quickly get the ID of a user. Then I think you could call the DD2 API with the user id directly to get their newest score. This would reduce from potentially searching 100 pages of the leaderboard per request to only do a cache lookup and then hit the API once.

Humm I think that's an interesting idea, I could have a cache of only players to uuid mapping, to do the research and take the best match with my similarity system and then call the DD2 API with this UUID that would fix the bug you though

**Comment by fantomitechno** [comment]
> Will the tm.io API only return the first result? I imagine it returns multiple and the issue with oops was that the implementation was getting the first match and not the closest(or in this case exact) match from the API.

No it returns more if needed (for Oops it returns, OopTM + goopTM) but like I said:
> if you use the API to search for simo900, mine will return simo_900, tm.io won't return anything

**Comment by DigitalAda** [comment]
We could probably speed it up even more if we want, but it is porbably not usefull to spend time on since this is a limited-time event.
